server:
  port: 8761

eureka:
  client: # EurekaClientConfigBean / EurekaServerConfigBean
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud: DEBUG